### ISSUE TITLE
[production][freereg1_csv_entries#destroy] undefined method `register' for nil:NilClass

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2287]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/5e887ac6e937905a70828d4f)

**Comment by Captainkirkdawson** [comment]
Started DELETE "/freereg1_csv_entries/5e22de52f493fd537928f406?locale=en" for 5.9.125.163 at 2020-05-11 14:53:37 +0100
Processing by Freereg1CsvEntriesController#destroy as HTML
  Parameters: {"authenticity_token"=>"W90RRdws9nmVWeTln4r2HX8PNQM54OKff2+AN+tWorrQq+XsqtHvBHJ6U0qQBbDTxwlgS8aK15nvVChU/V8ABQ==", "locale"=>"en", "id"=>"5e22de52f493fd537928f406"}
NoMethodError (undefined method `register' for nil:NilClass):
  
app/models/search_record.rb:950:in `update_location'
app/models/freereg1_csv_entry.rb:836:in `update_seach_record_location'
app/controllers/freereg1_csv_entries_controller.rb:107:in `destroy'

**Comment by Captainkirkdawson** [comment]
Believe to be fixed on test3
