### ISSUE TITLE
Images cannot be uploaded to refinery

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#417]
When Bernie attempts to upload images, the following error is thrown:

```

Started POST "/refinery/images?dialog=true" for 144.76.154.40 at 2015-02-10 09:48:13 +0000
Processing by Refinery::Admin::ImagesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"+Qvtq/gxhOty5MVnY01ri7jqVcM/dTyCJs/MewRKv1U=", "image"=>{"image"=>[#<ActionDispatch::Http::UploadedFile:0x000008193b2d08 @original_filename="FreeREG2 Revised Search 0.JPG", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"image[image][]\"; filename=\"FreeREG2 Revised Search 0.JPG\"\r\nContent-Type: image/jpeg\r\n", @tempfile=#<Tempfile:/tmp/RackMultipart20150210-42876-1pd1wyt>>]}, "wymeditor"=>"", "modal"=>"true", "dialog"=>"true", "app_dialog"=>"true", "field"=>"", "update_image"=>"", "thumbnail"=>"", "callback"=>"", "conditions"=>"", "locale"=>:en}
Completed 500 Internal Server Error in 1298.9ms

Dragonfly::DataStorage::UnableToStore (Permission denied - /home/apache/hosts/freereg2/production/public/system/refinery/images/2015/02):
  vendor/bundle/ruby/2.0/gems/dragonfly-0.9.15/lib/dragonfly/data_storage/file_data_store.rb:33:in `rescue in store'
  vendor/bundle/ruby/2.0/gems/dragonfly-0.9.15/lib/dragonfly/data_storage/file_data_store.rb:25:in `store'
  vendor/bundle/ruby/2.0/gems/dragonfly-0.9.15/lib/dragonfly/app.rb:95:in `store'
  vendor/bundle/ruby/2.0/gems/dragonfly-0.9.15/lib/dragonfly/job.rb:392:in `store'
  vendor/bundle/ruby/2.0/gems/dragonfly-0.9.15/lib/dragonfly/active_model_extensions/attachment.rb:179:in `store_job!'
  vendor/bundle/ruby/2.0/gems/dragonfly-0.9.15/lib/dragonfly/active_model_extensions/attachment.rb:74:in `save!'
  vendor/bundle/ruby/2.0/gems/dragonfly-0.9.15/lib/dragonfly/active_model_extensions/instance_methods.rb:16:in `block in save_dragonfly_attachments'
  vendor/bundle/ruby/2.0/gems/dragonfly-0.9.15/lib/dragonfly/active_model_extensions/instance_methods.rb:15:in `each'
  vendor/bundle/ruby/2.0/gems/dragonfly-0.9.15/lib/dragonfly/active_model_extensions/instance_methods.rb:15:in `save_dragonfly_attachments'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:407:in `_run__2200851430544389868__save__1885938946875252778__callbacks'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:264:in `create_or_update'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/persistence.rb:84:in `save'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/validations.rb:50:in `save'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/attribute_methods/dirty.rb:22:in `save'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:259:in `block in save'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:258:in `save'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/persistence.rb:45:in `create'
  vendor/bundle/ruby/2.0/gems/refinerycms-images-2.1.2/app/controllers/refinery/admin/images_controller.rb:47:in `block in create'
  vendor/bundle/ruby/2.0/gems/refinerycms-images-2.1.2/app/controllers/refinery/admin/images_controller.rb:46:in `each'
  vendor/bundle/ruby/2.0/gems/refinerycms-images-2.1.2/app/controllers/refinery/admin/images_controller.rb:46:in `create'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:524:in `_run__4569856525823602499__process_action__1585808825593087593__callbacks'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `block in action'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
  vendor/bundle/ruby/2.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  vendor/bundle/ruby/2.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  vendor/bundle/ruby/2.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
  vendor/bundle/ruby/2.0/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
  vendor/bundle/ruby/2.0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
  vendor/bundle/ruby/2.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  vendor/bundle/ruby/2.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  vendor/bundle/ruby/2.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
  vendor/bundle/ruby/2.0/gems/mongoid-3.1.6/lib/rack/mongoid/middleware/identity_map.rb:34:in `block in call'
  vendor/bundle/ruby/2.0/gems/mongoid-3.1.6/lib/mongoid/unit_of_work.rb:39:in `unit_of_work'
  vendor/bundle/ruby/2.0/gems/mongoid-3.1.6/lib/rack/mongoid/middleware/identity_map.rb:34:in `call'
  vendor/bundle/ruby/2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
  vendor/bundle/ruby/2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
  vendor/bundle/ruby/2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  vendor/bundle/ruby/2.0/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/2.0/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
  vendor/bundle/ruby/2.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  vendor/bundle/ruby/2.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  vendor/bundle/ruby/2.0/gems/dragonfly-0.9.15/lib/dragonfly/cookie_monster.rb:9:in `call'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
  vendor/bundle/ruby/2.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__3102696936983138947__call__1885938946875252778__callbacks'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  vendor/bundle/ruby/2.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
  vendor/bundle/ruby/2.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `block in call'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
  vendor/bundle/ruby/2.0/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
  vendor/bundle/ruby/2.0/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  vendor/bundle/ruby/2.0/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.0/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.0/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  vendor/bundle/ruby/2.0/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  vendor/bundle/ruby/2.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
  vendor/bundle/ruby/2.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
  vendor/bundle/ruby/2.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
  vendor/bundle/ruby/2.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
  vendor/bundle/ruby/2.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
  vendor/bundle/ruby/2.0/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
  vendor/bundle/ruby/2.0/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
  vendor/bundle/ruby/2.0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.53) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.53) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.53) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.53) lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

**Comment by juliancheal** [comment]
Is that on the live or staging?

Something is wrong with the permissions :(

**Comment by benwbrum** [comment]
I think I just fixed it.  It was the result of me moving the refinery assets onto a raid drive, but accidentally setting the ownership to my user account.

**Comment by benwbrum** [comment]
Bernie has been notified and will test the permissions change.
