### ISSUE TITLE
CSRF warnings on production

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#887]
After upgrading on production, we are getting CSRF warnings and InvalidAuthenticationToken exceptions.

Typical examples look like this:
```
App 7655 stdout: Started POST "/search_queries" for 5.9.125.163 at 2016-08-17 20:50:24 +0100
App 7655 stdout: Processing by SearchQueriesController#create as HTML
App 7655 stdout:   Parameters: {"utf8"=>"<E2><9C><93>", "authenticity_token"=>"XzcgdJIDHSeazJz7DjO1oQvqfM7C7COT7/QbjAlsaQY=", "search_query"=>{"last_name"=>"taylor", "first_name"=>"", "start_year"=>"", "end_year"=>"", "chapman_codes"=>["", "WRY"], "place_ids"=>["
53cd4995eca9ebee4f00b280"], "inclusive"=>"false", "search_nearby_places"=>"false", "fuzzy"=>"true", "region"=>""}, "button"=>""}
App 7655 stdout: Can't verify CSRF token authenticity
App 7655 stdout: Completed 422 Unprocessable Entity in 2ms (ActiveRecord: 0.0ms)
App 7682 stdout: 
App 7682 stdout: Started GET "/search_queries/new?search_id=57b4be62f4040b260a000b23" for 5.9.125.163 at 2016-08-17 20:50:25 +0100
App 7682 stdout: Processing by SearchQueriesController#new as HTML
App 7682 stdout:   Parameters: {"search_id"=>"57b4be62f4040b260a000b23"}
App 7655 stdout: ** [Airbrake] Failure: Net::HTTPInternalServerError
App 7655 stdout: 
App 7655 stdout: ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/actionpack-4.2.6/lib/action_controller/metal/request_forgery_protection.rb:181:in `handle_unverified_request'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/actionpack-4.2.6/lib/action_controller/metal/request_forgery_protection.rb:209:in `handle_unverified_request'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/devise-3.5.10/lib/devise/controllers/helpers.rb:257:in `handle_unverified_request'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/actionpack-4.2.6/lib/action_controller/metal/request_forgery_protection.rb:204:in `verify_authenticity_token'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:164:in `call'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:164:in `block in halting'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `each'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
App 7655 stdout:   vendor/bundle/ruby/2.2/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
```

**Comment by Captainkirkdawson** [comment]
Have removed CSRF requirement on a post to search queries.
Need comment on this being best long term solution

**Comment by Captainkirkdawson** [comment]
There are occasional other posts with errors  (1/day)

**Comment by Captainkirkdawson** [comment]
There ia agreement that this does not pose a security risk for search_queries
